S3_AUDIO_PATH = 'audio-files/'
S3_FULL_TEXT_PATH = 'full-transcripts/'
S3_SUMMARY_TEXT_PATH = 'summarized-text/'
S3_GLUED_AUDIO_PATH = 'audio-files-glued/'
S3_GLUED_ARCHIVED_AUDIO_PATH = 'audio-files-glued-archives/'
S3_TRANSCRIPTION_PATH = 'transcriptions/'
S3_HTML_PATH = 'html-files/'
TRANSCRIPTION_JOB_NAME = 'transcription-job'
PROMPT_TEXT = ('I have a large amount of police scanner audio that has been transcribed into text. '
               'The transcription may have inaccuracies, missing words, or phrases that don\'t make sense due to the '
               'limitations of the transcriber. I need you to process this text and provide me with a high-level '
               'overview of the key events and activities that took place. Ignore routine traffic stops, minor '
               'conversations, or general radio chatter unless they are directly relevant to a larger event. '
               'Where the transcription is unclear or garbled, do your best to infer the meaning based on context '
               'and provide a reasonable summary. They will be using the military alphabet, so whenever you read that'
               ' text, you should assume to use the first letter of the military alphabet words. '
               'Your response should be concise, organized, and focused on the '
               'bigger picture of what was happening on the police radio. When possible, you should include the location'
               ' where the incidents occurred (such as names of establishments, etc) as well as a description of all '
               'parties involved, but omit last names. The most popular street in Herndon is "Elden" street. So if you get "Elton" or '
               '"Elvin" or anything that sounds like Eldon street from the transcriber, assume it is Elden street. '
               'Please format the summary using the following HTML structure: '
               '    - Use <h3> tags for headlines. '
               '    - Use <p> tags for paragraphs.'
               '    - Use <ul> and <li> tags for bullet points.'
               '    - Ensure proper HTML syntax. You DO NOT need to include the beginning ```html and the end ``` , '
               'just include the HTML only please. You do not need to include the heading "Overview of Key Police Incidents". ')