S3_AUDIO_PATH = 'audio-files/'
S3_FULL_TEXT_PATH = 'full-transcripts/'
S3_SUMMARY_TEXT_PATH = 'summarized-text/'
S3_GLUED_AUDIO_PATH = 'audio-files-glued/'
S3_GLUED_ARCHIVED_AUDIO_PATH = 'audio-files-glued-archives/'
S3_TRANSCRIPTION_PATH = 'transcriptions/'
S3_HTML_PATH = 'html-files/'
TRANSCRIPTION_JOB_NAME = 'transcription-job'
PROMPT_TEXT = ('I have a large amount of police scanner audio that has been transcribed into text. '
               'The transcription may have inaccuracies, missing words, or phrases that don\'t make sense due to the '
               'limitations of the transcriber. I need you to process this text and provide me with a high-level '
               'overview of the key events and activities that took place. Focus only on significant incidents, '
               'such as crimes, emergencies, or major police operations. Ignore routine traffic stops, minor '
               'conversations, or general radio chatter unless they are directly relevant to a larger event. '
               'Where the transcription is unclear or garbled, do your best to infer the meaning based on context '
               'and provide a reasonable summary. Your response should be concise, organized, and focused on the '
               'bigger picture of what was happening on the police radio. Let me know if anything is unclear or if '
               'more clarification is needed.')